apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: pd-actions-amocsub
spec:
  replicas: 1
  template:
    spec:
      repository: amocsub/pd-actions
      dockerEnabled: false
      containers:
      - name: runnerkubectl
        securityContext:
          privileged: false
