parameters:
  probes: 
   - -sc # -sc, -status-code     display response status-code
   - -cl # -cl, -content-length  display response content-length
   - -ct # -ct, -content-type    display response content-type
   - -location # -location             display response redirect location
   - -favicon # -favicon              display mmh3 hash for '/favicon.ico' file
   - -hash md5 # -hash string          display response body hash (supported: md5,mmh3,simhash,sha1,sha256,sha512)
   - -jarm # -jarm                 display jarm fingerprint hash
   - -rt # -rt, -response-time   display response time
   - -lc # -lc, -line-count      display response body line count
   - -wc # -wc, -word-count      display response body word count
   - -title # -title                display page title
   - -server # -server, -web-server  display server name
   - -td # -td, -tech-detect     display technology in use based on wappalyzer dataset
   - -method # -method               display http request method
   - -websocket # -websocket            display server using websocket
   - -ip # -ip                   display host ip
   - -cname # -cname                display host cname
   - -asn # -asn                  display host asn information
   - -cdn # -cdn                  display cdn in use
   - -probe # -probe                display probe status