name: "full"

on:
  workflow_dispatch:
    inputs:
      input_domain:
        description: "Apex Domain to scan and add to the workflow"
        required: true
      ports_to_scan:
        description: "Port list to probe"
        default: "80,81,300,443,591,593,832,981,1010,1311,2082,2087,2095,2096,2480,2375,3000,3128,3333,4443,4080,4243,4567,4711,4712,4993,5000,5104,5108,5800,6543,7000,7396,7474,8000,8001,8008,8014,8042,8069,8080,8081,8088,8090,8091,8118,8123,8172,8222,8243,8280,8281,8333,8443,8500,8834,8880,8888,8983,9000,9043,9060,9080,9090,9091,9200,9443,9800,9981,10000,10250,12443,16080,18091,18092,20720,28017"

jobs:
  full:
    runs-on: pd-actions
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - id: subfinder
      run: subfinder -d ${{ github.event.inputs.input_domain }} -o workspace/subfinder-output -config config/subfinder/general.yaml
    - id: dnsx
      run: dnsx -l workspace/subfinder-output -o workspace/dnsx-output -t 5 -r config/resolvers.txt
    - id: naabu
      run: naabu -l workspace/dnsx-output -port ${{ github.event.inputs.ports_to_scan }} -c 25 -o workspace/naabu-output -r config/resolvers.txt
    - id: httpx
      run: httpx -l workspace/naabu-output -t 25 -o workspace/httpx-output -r config/resolvers.txt -random-agent false -H 'User-Agent:Mozilla/5.0 (compatible; PlatSec)'
    - id: nuclei
      run: nuclei -config config/nuclei/general.yaml -l workspace/httpx-output
    - id: add-subfinder
      run: cat workspace/subfinder-output | anew output/subfinder-output > workspace/new-subfinder-output
      if: steps.subfinder.outcome == 'success'
    - id: add-dnsx
      run: cat workspace/dnsx-output | anew output/dnsx-output > workspace/new-dnsx-output
      if: steps.dnsx.outcome == 'success'
    - id: add-naabu
      run: cat workspace/naabu-output | anew output/naabu-output > workspace/new-naabu-output
      if: steps.naabu.outcome == 'success'
    - id: add-httpx
      run: cat workspace/httpx-output | anew output/httpx-output > workspace/new-httpx-output
      if: steps.httpx.outcome == 'success'
    - id: add-nuclei
      run: cat workspace/nuclei-output | anew output/nuclei-output > workspace/new-nuclei-output
      if: steps.nuclei.outcome == 'success'
    - run: |
        git add output/
        git config --local user.email "${{ secrets.GLOBAL_GITHUB_EMAIL }}"
        git config --global user.name "${{ secrets.GLOBAL_GITHUB_USER }}"
        git commit -m "${{ github.workflow }} - Run ${{ github.run_id }} - Add ${{ github.event.inputs.input_domain }}" -a --allow-empty
        git push -f
      if: steps.add-subfinder.outcome == 'success' || steps.add-dnsx.outcome == 'success' || steps.add-naabu.outcome == 'success' || steps.add-httpx.outcome == 'success' || steps.add-nuclei.outcome == 'success'