name: "httpx"

on:
  workflow_dispatch:
    inputs:
      input_filename:
        description: "File name with all the subdomains with ports to scan"
        default: "input/httpx-input"
      output_filename:
        description: "Where to put the results"
        default: "output/httpx-output"
      amount_of_workers:
        description: "How many workers should be used, max 256 per matrix"
        default: "5"
      config_folder:
        default: "config/httpx/general/*"
        description: "Folder containing httpx configurations files"
  # schedule:
  # # * is a special character in YAML so you have to quote this string
  # - cron:  '30 5,17 * * *'

jobs:
  split:
    runs-on: pd-actions
    outputs:
      splited_files: ${{ steps.split.outputs.splited_files }}
    steps:
    - uses: actions/checkout@v3
    - name: Split files
      id: split
      run: |
        mkdir -p workspace/split && rm -rf workspace/split/*
        lines_per_file=$((($(wc -l < "${{ github.event.inputs.input_filename || 'input/httpx-input' }}") + ${{ github.event.inputs.amount_of_workers || '5' }} - 1) / ${{ github.event.inputs.amount_of_workers || '5' }}))
        split -l ${lines_per_file} "${{ github.event.inputs.input_filename || 'input/httpx-input' }}" workspace/split/
        files_array=$(find workspace/split/* -printf "%f\n" | jq -R -s -c 'split("\n")[:-1]')
        echo "splited_files=${files_array}" >> $GITHUB_OUTPUT
        gcloud storage cp workspace/split/* gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/split/

  httpx:
    needs: split
    runs-on: pd-actions
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.split.outputs.splited_files) }}
    steps:
    - uses: actions/checkout@v3
    - name: Run httpx
      run: |
        gcloud storage cp gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/split/${{ matrix.file }} workspace/httpx-input
        mkdir -p /home/runner/.config/httpx
        cp -r ${{ github.event.inputs.config_folder || 'config/httpx/general/*' }} /home/runner/.config/httpx
        httpx
        gcloud storage cp workspace/httpx-output gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/httpx/httpx-output-${{ matrix.file }}

  merge_save:
    needs: httpx
    runs-on: pd-actions
    if: ${{ always() && contains(needs.*.result, 'success') }}
    steps:
    - uses: actions/checkout@v3
    - name: Download & Merge
      run: |
        gcloud storage cp "gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/httpx/*" workspace/
        jq -scr 'unique[]' workspace/httpx-output-* | anew ${{ github.event.inputs.output_filename || 'output/httpx-output' }} > news/httpx-news
    - name: Prepare Next
      run: |
        jq -scr 'map({(.url):1})|add|keys_unsorted | .[]' output/httpx-output > input/nuclei-input
    - name: Save Results
      run: |
        git add input/* output/* news/*
        git config --local user.email "${{ secrets.GLOBAL_GITHUB_EMAIL }}"
        git config --global user.name "${{ secrets.GLOBAL_GITHUB_USER }}"
        git commit -m "${{ github.workflow }} - Run ${{ github.run_id }}" -a --allow-empty
        git push -f

  alert:
    needs: [split, httpx, merge_save]
    runs-on: pd-actions
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
    - run: |
        curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H "Content-type: application/json" \
          -d '{ "text": "Github Actions Workflow ${{ github.workflow }} status failure - <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Link>" }'
      