name: "naabu"

on:
  workflow_dispatch:
    inputs:
      input_filename:
        description: "File name with all the subdomains to scan"
        default: "output/active-subdomains.txt"
      output_filename:
        description: "Where to put the results"
        default: "output/active-ports.txt"
      amount_of_workers:
        description: "How many workers should be used, max 256 per matrix"
        default: "5"
      threads_per_worker:
        description: "How many threads per worker should be used"
        default: "25"
      ports_to_scan:
        description: "Port list to probe"
        default: "80,81,300,443,591,593,832,981,1010,1311,2082,2087,2095,2096,2480,2375,3000,3128,3333,4443,4080,4243,4567,4711,4712,4993,5000,5104,5108,5800,6543,7000,7396,7474,8000,8001,8008,8014,8042,8069,8080,8081,8088,8090,8091,8118,8123,8172,8222,8243,8280,8281,8333,8443,8500,8834,8880,8888,8983,9000,9043,9060,9080,9090,9091,9200,9443,9800,9981,10000,10250,12443,16080,18091,18092,20720,28017"
  # schedule:
  # # * is a special character in YAML so you have to quote this string
  # - cron:  '30 5,17 * * *'

jobs:
  split:
    runs-on: pd-actions
    outputs:
      splited_files: ${{ steps.split.outputs.splited_files }}
    steps:
    - uses: actions/checkout@v3
    - id: split
      run: |
        mkdir -p workspace/split && rm -rf workspace/split/*
        lines_per_file=$((($(wc -l < "${{ github.event.inputs.input_filename }}") + ${{ github.event.inputs.amount_of_workers }} - 1) / ${{ github.event.inputs.amount_of_workers }}))
        split -l ${lines_per_file} "${{ github.event.inputs.input_filename }}" workspace/split/
        files_array=$(find workspace/split/* -printf "%f\n" | jq -R -s -c 'split("\n")[:-1]')
        echo "splited_files=${files_array}" >> $GITHUB_OUTPUT
        gcloud storage cp workspace/split/* gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/split/

  naabu:
    needs: split
    runs-on: pd-actions
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.split.outputs.splited_files) }}
    steps:
    - uses: actions/checkout@v3
    - run: |
        gcloud storage cp gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/split/${{ matrix.file }} workspace/active-subdomains-to-scan.txt
        naabu -l workspace/active-subdomains-to-scan.txt -port ${{ github.event.inputs.ports_to_scan }} -c ${{ github.event.inputs.threads_per_worker }} -o workspace/naabu-output-${{ matrix.file }}
        gcloud storage cp workspace/naabu-output-* gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/naabu/  

  merge_save:
    needs: naabu
    runs-on: pd-actions
    if: ${{ always() && contains(needs.*.result, 'success') }}
    steps:
    - uses: actions/checkout@v3
    - run: |
        gcloud storage cp "gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/naabu/*" workspace/
        cat workspace/naabu-output-* | anew ${{ github.event.inputs.output_filename }} > workspace/new-active-ports.txt
        git add ${{ github.event.inputs.output_filename }}
        git config --local user.email "${{ secrets.GLOBAL_GITHUB_EMAIL }}"
        git config --global user.name "${{ secrets.GLOBAL_GITHUB_USER }}"
        git commit -m "${{ github.workflow }} - Run ${{ github.run_id }}" -a --allow-empty
        git push -f

  alert:
    needs: [split, naabu, merge_save]
    runs-on: pd-actions
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
    - run: |
        curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H "Content-type: application/json" \
          -d '{ "text": "Github Actions Workflow ${{ github.workflow }} status failure - <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Link>" }'
      