name: "subfinder"

on:
  workflow_dispatch:
    inputs:
      input_filename:
        description: "File name with all the apex domains to scan"
      output_filename:
        description: "Where to put the results"
      amount_of_workers:
        description: "How many workers should be used, max 256 per matrix"
      config_file:
        description: "File containing subfinder configurations"
  # schedule:
    # # * is a special character in YAML so you have to quote this string
    # - cron:  '0 0 * * *'

jobs:
  
  split:
    runs-on: pd-actions
    outputs:
      splited_files: ${{ steps.split.outputs.splited_files }}
    steps:
    - uses: actions/checkout@v3
    - id: split
      run: |
        mkdir -p workspace/split && rm -rf workspace/split/*
        lines_per_file=$((($(wc -l < "${{ github.event.inputs.input_filename || 'input/subfinder-input' }}") + ${{ github.event.inputs.amount_of_workers || '5' }} - 1) / ${{ github.event.inputs.amount_of_workers || '5' }}))
        split -l ${lines_per_file} "${{ github.event.inputs.input_filename || 'input/subfinder-input' }}" workspace/split/
        files_array=$(find workspace/split/* -printf "%f\n" | jq -R -s -c 'split("\n")[:-1]')
        echo "splited_files=${files_array}" >> $GITHUB_OUTPUT
        gcloud storage cp workspace/split/* gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/split/
  
  subfinder:
    needs: split
    runs-on: pd-actions
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.split.outputs.splited_files) }}
    steps:
    - uses: actions/checkout@v3
    - run: |
        gcloud storage cp gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/split/${{ matrix.file }} workspace/domains-to-scan.txt
        subfinder -config ${{ github.event.inputs.config_file || 'config/subfinder/general.yaml' }}
        gcloud storage cp workspace/subfinder-output gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/subfinder/subfinder-output-${{ matrix.file }}

  merge_save:
    needs: subfinder
    runs-on: pd-actions
    if: ${{ always() && contains(needs.*.result, 'success') }}
    steps:
    - uses: actions/checkout@v3
    - name: Download & Merge
      run: |
        gcloud storage cp "gs://pd-actions-bucket-dev/runs/${{ github.run_id }}/subfinder/*" workspace/
        jq -scr 'unique[]' workspace/subfinder-output-* | anew ${{ github.event.inputs.output_filename || 'output/subfinder-output' }} > news/subfinder-news
        cat workspace/subfinder-output-* 
    - name: Prepare Next
      run: |
        jq -scr '.[] | try .host' output/subfinder-output > input/dnsx-input
    - name: Save Results
      run: |
        git add input/* output/* news/*
        git config --local user.email "${{ secrets.GLOBAL_GITHUB_EMAIL }}"
        git config --global user.name "${{ secrets.GLOBAL_GITHUB_USER }}"
        git commit -m "${{ github.workflow }} - Run ${{ github.run_id }}" -a --allow-empty
        git push -f

  alert:
    needs: [split, subfinder, merge_save]
    runs-on: pd-actions
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
    - run: |
        curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H "Content-type: application/json" \
          -d '{ "text": "Github Actions Workflow ${{ github.workflow }} status failure - <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Link>" }'
